### ISSUE TITLE
Character issues

### ISSUE THREAD

**Issue by arosyfinch** [Swiftzerr/AlbumPosterGenerator#10]
When using albums with long titles or artists with longer names, the text either overruns with the release date or, if split into two lines, overlaps with the album cover art. Would it be possible to shrink the artist name if it would otherwise overlap with other text?

I also encountered an album which didn't display the tracklist; this could be because the characters are non-latin. would it be possible to add a basic font with wider character support for such cases?

**Comment by Swiftzerr** [comment]
I thought about shrinking text and splitting into 2 lines so that it would fit. I will look more into this

**Comment by Swiftzerr** [comment]
Also custom font support may be possible but difficult rn

**Comment by arosyfinch** [comment]
Thanks for the reply! I think the songs which turned up blank had parentheses in the title, it's probably messing with the code pulling the title text.
![daughter stereo mind game](https://github.com/Swiftzerr/AlbumPosterGenerator/assets/150024726/4b547727-00a4-4963-bd4c-8e181373498e)
In this example the missing track name is (Missed Calls)

**Comment by arosyfinch** [comment]
I'd also like to say I'm really grateful for the program! I've put a bunch up in my room, you've saved it from looking barren haha
![IMG_9831](https://github.com/Swiftzerr/AlbumPosterGenerator/assets/150024726/98a01eb9-2f21-4e79-8ccf-0f9c7ad99b5f)

**Comment by Swiftzerr** [comment]
Oh I see what you mean. That's actually due to some lazy code I wrote to get rid of (feat. ___) tags. It just looks for any parenthesis and gets rid of them. I didn't assume that would be an issue haha. I'll fix it up later today to actually look for the feature text instead of removing everything in parenthesis. Glad I could make your room more interesting. Thanks for reporting!

**Comment by elliotjarnit** [comment]
I added a new feature which allows you to edit the poster including the tracklist. This means you can edit the names of an tracks if they don't appear.
